### ISSUE TITLE
Replace iconUrl with text 

### ISSUE THREAD

**Issue by Sandeep3005** [InboxSDK/hello-world#2]
HI 

Can we replace iconUrl with text value - so instead of icon I want to create a button with text  'Add Greeting'

Can we do that?

**Comment by ottograjeda** [comment]
Can someone share an actual / REAL ( as in code working) screenshot ?

**Comment by Macil** [comment]
@ottograjeda We've added a screenshot to the [repo's readme](https://github.com/InboxSDK/hello-world). Please open new issues for any other questions.

**Comment by Macil** [comment]
We don't support adding a button to the compose with just a text label, because it would be inconsistent with Gmail's Compose buttons and it would be much too crowded to fit.
