### ISSUE TITLE
Instructions no longer work

### ISSUE THREAD

**Issue by doctaphred** [InboxSDK/hello-world#3]
README.md references an `npm start` command, which was removed in 339f90b9ad39ea837de013079cb808310d3c90bf. Here's what happens when I run it:
```
$ npm start

npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frederick/.npm/_logs/2022-02-28T17_39_51_389Z-debug-0.log

$ npm run

Scripts available in hello-world@0.1.0 via `npm run-script`:
  clean
    rimraf dist
  build
    webpack --config webpack.dev.js
  build-prod
    webpack --config webpack.prod.js
```
I was able to install the unpacked extension created in the `dist` directory via the `npm run build` command, so I think the instructions just need to be updated to match.

**Comment by Macil** [comment]
Thanks for pointing this out! This was overlooked when this repo was moved over to using webpack. An `npm start` command that runs webpack in --watch mode has been added.
